esphome:
  name: dmx-example

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

external_components:
  - source: components

# DMX bus setup
dmx:
  - id: dmx_bus_a
    name: "DMX Port 1"
    mode: send
    wait_for_send: true
    enabled: true
    send_timeout_ticks: 100
    receive_timeout_ticks: 100
    enable_pin:
      number: GPIO18
    tx_pin:
      number: GPIO16
    rx_pin:
      number: GPIO17
    dmx_port_id: 1

  - id: dmx_bus_b
    name: "DMX Port 2"
    mode: receive
    enable_pin:
      number: GPIO23
    tx_pin:
      number: GPIO21
    rx_pin:
      number: GPIO22
    dmx_port_id: 2

# DMX bus channels as sensors
sensor:
  - platform: dmx
    dmx_bus_id: dmx_bus_b
    channel: 3
    id: dmx_sensor_1
    name: "DMX Channel 1 Value"
    on_value:
      then:
        - light.turn_on:
            id: gpio_light
            brightness: !lambda "return x / 255.0;"

  - platform: dmx
    dmx_bus_id: dmx_bus_b
    channel: 2
    id: dmx_sensor_2
    name: "DMX Channel 2 Value"

# DMX fixtures as outputs
output:
  - platform: dmx
    id: dmx_output_1
    dmx_bus_id: dmx_bus_a
    channel: 1

  - platform: dmx
    id: dmx_output_2
    dmx_bus_id: dmx_bus_a
    channel: 2

  - platform: dmx
    id: dmx_output_3
    dmx_bus_id: dmx_bus_a
    channel: 3

  # Internal output for synced light (synced to DMX sensor channel 1)
  - platform: ledc
    id: gpio_ledc_output
    pin: GPIO2

# Example: set up dmx output fixtures as lights
light:
  - platform: monochromatic
    name: "DMX Light 1"
    output: dmx_output_1

  - platform: rgb
    name: "DMX RGB Light"
    red: dmx_output_1
    green: dmx_output_2
    blue: dmx_output_3

  - platform: monochromatic
    name: "Light driven by DMX channel"
    id: gpio_light
    output: gpio_ledc_output

# Example switch with lambda operating on DMX component
switch:
  - platform: template
    name: "DMX Channel 1 Full Brightness"
    turn_on_action:
      lambda: |-
        // Fetch the DMX component by ID
        auto dmx_bus = id(dmx_bus_a);
        // Write full brightness (255) to channel 1
        dmx_bus->send_channel(1, 255);
    turn_off_action:
      lambda: |-
        // Fetch the DMX component by ID
        auto dmx_bus = id(dmx_bus_a);
        // Write 0 to channel 1
        dmx_bus->send_channel(1, 0);
